theme = "nord-night"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[keys.normal]
y = ["yank_to_clipboard"]

[keys.select]
y = ["yank_to_clipboard"]
