[global]
# List of rules to disable.
disable = ["MD033"]
# Additional rules to enable on top of defaults (additive).
extend-enable = ["ALL"]
# Additional rules to disable on top of the disable list (additive).
extend-disable = []
# List of file/directory patterns to exclude from linting.
exclude = ["**/node_modules/**"]
