#!/bin/sh

# Purpose: check conventional commits
# Usage: make this script the git post-commit hook
# Dependencies: cocogitto
# Date: 2025-09-02
# Author: Yusong

set -e

# Check the latest commit message.
if ! cog check HEAD..HEAD >/dev/null 2>&1; then
  echo "Error: Commit message violates conventional commits."
  cog check HEAD..HEAD
  exit 1
fi

# Git LFS.
command -v git-lfs >/dev/null 2>&1 || {
  printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-commit' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."
  exit 2
}
git lfs post-commit "$@"
