#!/bin/sh

# Purpose: check conventional commits for those not pushed
# Usage: make this script the git pre-push hook
# Dependencies: cocogitto
# Date: 2025-09-02
# Author: Yusong

set -e

# Check commit messages that haven't been pushed.
if ! cog check origin/HEAD..HEAD >/dev/null 2>&1; then
  echo "Error: Commit message(s) violates conventional commits."
  cog check origin/HEAD..HEAD
  exit 1
fi

# Git LFS.
command -v git-lfs >/dev/null 2>&1 || {
  printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."
  exit 2
}
git lfs pre-push "$@"
