name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  spelling:
    runs-on: ubuntu-latest
    name: spell check with typos
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Run typos command
        shell: nix develop --quiet --command bash {0}
        run: |
          sh ./scripts/check-typos-in-files.sh
